language: android

android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra

after_script:
    - cat ./demo/build/outputs/lint-results.xml
    - cat ./library/build/outputs/lint-results.xml
    - cat ./utils-picasso/build/outputs/lint-results.xml

sudo: false