language: android

android:
  components:
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-m2repository

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

jdk:
  - oraclejdk8

script:
  - ./gradlew clean connectedCheck --stacktrace

after_success:
  - gradle/deploy_snapshot.sh

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
